name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Package CLI Tool
        if: github.event_name == 'push'
        run: |
          npm install -g pkg
          pkg index.js --targets node16-linux-x64,node16-macos-x64,node16-win-x64 --output motivational-quote-cli
          
      - name: Upload Release Asset
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: motivational-quote-cli
          path: motivational-quote-cli
